config/routes.rb
Rails.application.routes.draw do
  resources :pictures

  resources :my_works

  resources :faqs

  resources :users

  root 'static_pages#home'

  get 'about_me', to: 'about_me#show'
  get 'about_me/edit', to: 'about_me#edit'
  post 'about_me/update', to: 'about_me#update'

  get 'contact_me', to: 'contact_me#show'
  get 'contact_me/edit', to: 'contact_me#edit'
  post 'contact_me/update', to: 'contact_me#update'
  post 'contact_me', to: 'contact_me#contact_me'

  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'

  get '/signup' => 'users#new'

end

app/models/faq.rb
class Faq < ActiveRecord::Base
	validates_presence_of :question, :answer
end

app/controllers/faqs_controller.rb
class FaqsController < ApplicationController
  before_action :set_faq, only: [:show, :edit, :update, :destroy]
  before_action :authenticated_admin?, except: [:index]
  # GET /faqs
  # GET /faqs.json
  def index
    @subsection = 'FAQs'
    @faqs = Faq.all.order("LOWER(question)")
  end

  # GET /faqs/new
  def new
    @subsection = 'New FAQ'
    @faq = Faq.new
  end

  # GET /faqs/1/edit
  def edit
  end

  def show
    redirect_to faqs_path and return
  end

  # POST /faqs
  # POST /faqs.json
  def create
    @faq = Faq.new(faq_params)

    if @faq.save
      redirect_to faqs_path, notice: 'Faq was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /faqs/1
  # PATCH/PUT /faqs/1.json
  def update
    if @faq.update(faq_params)
      redirect_to faqs_path, notice: 'Faq was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /faqs/1
  # DELETE /faqs/1.json
  def destroy
    @path = false
    @faq.destroy
    redirect_to faqs_path, notice: 'Faq was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_faq
      @faq = Faq.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def faq_params
      params.require(:faq).permit(:question, :answer)
    end
end

app/helpers/faqs_helper.rb
module FaqsHelper
end

app/views/faqs/_admin_options.html.haml
.dropdown
  %a.no-hover-effects{"aria-expanded" => "false", "data-toggle" => "dropdown", :type => "button", data: { class: "admin-options" }}
    %span.glyphicon.glyphicon-cog.tf-options{"aria-hidden" => "true", :title => "options"}
  %ul.dropdown-menu.dropdown-options{:role => "menu"}
    %li
      = link_to 'Edit', edit_faq_path(faq.id)
    %li
      = link_to 'Destroy', faq, method: :delete, data: { confirm: 'Are you sure?' }

app/views/faqs/_faq.html.haml
- @faqs.each do |faq|
  %span.faq-goto{id: "question-#{faq.id}"}
  .row.faq-question{ class: "question_#{faq.id}_flash" }
    .col-sm-11
      = faq.question
    .col-sm-1.text-right
      - if current_user && current_user.admin?
        = render partial: 'faqs/admin_options', locals: { faq: faq }
  .row.faq-answer
    .col-sm-12
      %p
        = faq.answer

app/views/faqs/_form.html.haml
= form_for @faq do |f|
  - if @faq.errors.any?
    #error_explanation
      %h2= "#{pluralize(@faq.errors.count, "error")} prohibited this faq from being saved:"
      %ul
        - @faq.errors.full_messages.each do |msg|
          %li= msg

  .field.form-group
    = f.label :question
    = f.text_field :question, class: 'form-control'
  .field.form-group
    = f.label :answer
    = f.text_area :answer, class: 'form-control faq-edit-answer'
  .actions
    = f.submit 'Save'

app/views/faqs/_question.html.haml
- link = fq.question == 'NEW FAQ' ? fq.answer : "#question-#{fq.id}"
%a.faq-search.no-hover-effects{href: "#{link}", data: { question: "#{fq.id}" }}
  %span.glyphicon.glyphicon-chevron-right{"aria-hidden" => "true"}
  = fq.question
  %br
  %hr.question-hr

app/views/faqs/edit.html.haml
%h1 Editing FAQ

= render 'form'

= link_to 'Back', faqs_path, class: 'btn btn-blue'

app/views/faqs/index.html.haml
.row
  .col-sm-10.col-sm-offset-1.main-container.faq-main
    %h1.text-center.ntf Frequenty Asked Questions
    - if current_user && current_user.admin?
      .new-work
        %a.no-decoration.btn.btn-xs{href: "#{new_faq_path}"}
          %span.glyphicon.glyphicon-plus{title: 'New Faq'}
    .row
      .col-sm-10.col-sm-offset-1.faq-questions.faq-questions
        - @faqs.each do |fq|
          = render partial: 'question', locals: { fq: fq }
.row
  .col-sm-10.col-sm-offset-1  
    #faq-section
      = render partial: 'faq'
    %br
    %p
      = link_to "To The Top!", '#top', class: 'btn btn-purple btn-xs'

app/views/faqs/new.html.haml
.row
  .col-sm-10.col-sm-offset-1.round-corners.main-container
    %h1 New FAQ

    = render 'form'

    = link_to 'Back', faqs_path, class: 'btn btn-blue'