config/routes.rb
Rails.application.routes.draw do
  resources :pictures

  resources :my_works

  resources :faqs

  resources :users

  root 'static_pages#home'

  get 'about_me', to: 'about_me#show'
  get 'about_me/edit', to: 'about_me#edit'
  post 'about_me/update', to: 'about_me#update'

  get 'contact_me', to: 'contact_me#show'
  get 'contact_me/edit', to: 'contact_me#edit'
  post 'contact_me/update', to: 'contact_me#update'
  post 'contact_me', to: 'contact_me#contact_me'

  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'

  get '/signup' => 'users#new'

end

app/models/my_work.rb
class MyWork < ActiveRecord::Base
	has_many :pictures, as: :gallery, dependent: :destroy
  before_save :set_tags

	def cover?
		return self.picture_id.present? ? true : false
	end

	def cover
		return Picture.find_by_id(self.picture_id) if self.cover?
		return nil
	end

  private

  def set_tags
    tags = self.tags.split(',').map { |tag| tag.downcase.strip }
    self.tags = tags.join(', ')
  end
end

app/controllers/my_works_controller.rb
class MyWorksController < ApplicationController
  before_action :set_my_work, only: [:show, :edit, :update, :destroy]
  before_action :authenticated_admin?, except: [:index, :show]

  # GET /my_works
  # GET /my_works.json
  def index
    if current_user && current_user.admin?
      @my_works = MyWork.all.order(:created_at)
    else
      @my_works = MyWork.all.where(published: true).order(:created_at)
    end
  end

  # GET /my_works/1
  # GET /my_works/1.json
  def show
    if @my_work.published? || ( current_user && current_user.admin? )
      @pictures = []
      @pictures << @my_work.cover if @my_work.cover?
      @pictures += @my_work.pictures.cropped.where.not(id: @my_work.cover.id) if @my_work.cover
    else
      flash[:notice] = "You must be an admin to visit that page"
      redirect_to root_path
    end
  end

  # GET /my_works/new
  def new
    @my_work = MyWork.new
  end

  # GET /my_works/1/edit
  def edit
    @pictures = @my_work.pictures
  end

  # POST /my_works
  # POST /my_works.json
  def create
    @my_work = MyWork.new(my_work_params)
    respond_to do |format|
      if @my_work.save
        # if params[:images]
          # The magic is here ;)
          # params[:images].each { |image|
            # @my_work.pictures.create(image: image)
          # }
        # end
        format.html { redirect_to @my_work, notice: 'My work was successfully created.' }
        format.json { render :show, status: :created, location: @my_work }
      else
        format.html { render :new }
        format.json { render json: @my_work.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /my_works/1
  # PATCH/PUT /my_works/1.json
  def update
    @my_work.update_attribute(:published, true)
    # params["my_work"]["tags"] = params["my_work"]["tags"].split(' ').uniq.join(' ') if params["my_work"] && params["my_work"]["tags"] && params["my_work"]["tags"].present?
    respond_to do |format|
      if @my_work.update(my_work_params)
        format.html { redirect_to @my_work, notice: 'My work was successfully updated.' }
        format.json { render :show, status: :ok, location: @my_work }
      else
        format.html { render :edit }
        format.json { head :ok }
      end
    end
  end

  # DELETE /my_works/1
  # DELETE /my_works/1.json
  def destroy
    @my_work.destroy
    respond_to do |format|
      format.html { redirect_to my_works_url, notice: 'My work was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_my_work
      @my_work = MyWork.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def my_work_params
      params.require(:my_work).permit(:title, :published, :tags, :description, :picture_id, :pictures)
    end
end

app/helpers/my_works_helper.rb
module MyWorksHelper
end

app/views/my_works/_admin_options.html.haml
.dropdown.pull-right
  %a.no-hover-effects{"aria-expanded" => "false", "aria-haspopup" => "true", "data-toggle" => "dropdown", :type => "button"}
    %span.glyphicon.glyphicon-cog.tf-options{"aria-hidden" => "true"}
  %ul.dropdown-menu{"aria-labelledby" => "dLabel", :role => "menu"}
    %li
      = link_to 'Edit', edit_my_work_path(my_work)
    %li
      = link_to 'Destroy', my_work, method: :delete, data: { confirm: 'Are you sure? I can NOT undo this.' }

app/views/my_works/_description.html.haml
#my-work-show-info
  - if current_user && current_user.admin?
    .hidden-xs
      = render partial: 'admin_options', locals: { my_work: @my_work }
  %div.text-center.hidden-xs
    %h3.text-center.remove-top-margin
      = @my_work.title
  - if @my_work.tags.length > 0 && current_user && current_user.admin?
    %p.text-center
      - @my_work.tags.split(',').each do |tag|
        %span.badge
          = tag
  - if @my_work.description.length > 0
    %hr
    %p
      = @my_work.description.html_safe

app/views/my_works/_form.html.haml
= form_for @my_work, html: { class: 'form-horizontal', multipart: true } do |f|
  - if @my_work.errors.any?
    #error_explanation
      %h2= "#{pluralize(@my_work.errors.count, "error")} prohibited this my_work from being saved:"
      %ul
        - @my_work.errors.full_messages.each do |msg|
          %li= msg
  .form-group
    = f.label :title, class: 'control-label'
    .controls
      = f.text_field :title, class: 'form-control'
  .form-group
    = f.label :published, class: 'control-label'
    .controls
      = f.check_box :published, class: 'form-control'
  .form-group
    = f.label :tags, class: 'control-label'
    .controls
      = f.text_field :tags, class: 'form-control'
  .form-group
    = f.label :description, class: 'control-label'
    .controls
      = f.cktext_area :description, class: 'form-control', :ckeditor => {:uiColor => '#8400ff'}
  .form-actions
    = f.submit nil, class: 'btn btn-blue btn-large'

app/views/my_works/_full_image.html.haml
.tab-content
  - active = true
  - @pictures.each_with_index do |pic,index|
    .tab-pane{class: "#{index==0 ? 'active' : ''}", :role => "tabpanel", id: "#{pic.name_id}"}
      .my-work-main-image.img-responsive
        %img.picture-ajax{data: {id: "#{pic.id}", size: 'large'}}
        - active = false

app/views/my_works/_image_dropzone.html.haml
%br
  .text-center
    Changes to this page do not to be saved it is done automagically.
%form.dropzone#myAwesomeDropzone{:action => "/pictures"}
%input{:type => "hidden", :value => "#{@my_work.id}", :id =>'gallery_id'}
%input{:type => "hidden", :value => "#{@my_work.class.to_s}", :id =>'gallery_type'}
%input{:type => "hidden", :value => "#{form_authenticity_token}", :id =>'session_key'}

%div.tabpanel#my-work-edit-images
  / Nav tabs
  %ul.nav.nav-tabs#ul-tab
    %li.active
      %a.tab-load.ajaxed{:href => "#pictures"} 
        Pictures
    - @my_work.pictures.each do |picture|
      %li{id: "#{picture.name_id}-tab"}
        %a.tab-load{:href => "#", class: "#{picture.cropped ? '' : 'not-cropped'}", data: { id: "#{picture.id}", file_name: "#{picture.image_file_name_no_ext}" }} 
          - if picture.title.present?
            = picture.title
          - else
            =picture.image_file_name_no_ext
  / Tab panes
  .tab-content#tab-content
    .tab-pane.active{id: "pictures"}
      :javascript
          $(document).ready(function() {
            $.ajax({
              type: "GET",
              url: "/pictures?gallery_id="+"#{@my_work.id}"+"&gallery_type=MyWork",
              success: function(data, textStatus, jqXHR) {
                $('#pictures').html(data);
                $('.delete-image').on("click", deleteImage);
                return $('.update-main-image').on("change", updateMainImage);
              }
            });
          });
      = render partial: 'pictures/index', locals: { pictures: @pictures}
    - @my_work.pictures.each do |picture| 
      .tab-pane{id: "#{picture.name_id}-content"}

app/views/my_works/_thumbnail_list.html.haml
%ul.nav{:role => "tablist"}
  - active = true
  %li{:role => "presentation",class: "#{active ? 'active' : ''}"}
    - @pictures.each do |pic|
      .my-work-thumbnails
        %a{"aria-controls" => "home", "data-toggle" => "tab", :href => "##{pic.name_id}", :role => "tab"}
          %img.picture-ajax.thumbnail-img{data: {id: "#{pic.id}", size: 'large'}}
          - active = false

app/views/my_works/edit.html.haml
.row
  .col-sm-10.col-sm-offset-1.main-container.round-corners
    .row
      .col-sm-10.col-sm-offset-1
        %h1.text-center.ntf Editing Work
        %div{:role => "tabpanel"}
          / Nav tabs
          %ul.nav.nav-tabs{:role => "tablist"}
            %li.active{:role => "presentation"}
              %a{"aria-controls" => "home", "data-toggle" => "tab", :href => "#form", :role => "tab"} My Work
            %li{:role => "presentation"}
              %a{"aria-controls" => "profile", "data-toggle" => "tab", :href => "#images", :role => "tab"} Images
          / Tab panes
          .tab-content
            #form.tab-pane.active{:role => "tabpanel"}
              = render partial: 'form'
            #images.tab-pane{:role => "tabpanel"}
              = render partial: 'image_dropzone'
        %br
        = link_to 'Show', @my_work, class: 'btn btn-purple btn-xs'
        \|
        = link_to 'Back', my_works_path, class: 'btn btn-purple btn-xs'

app/views/my_works/index.html.haml
.row
  .col-sm-10.col-sm-offset-1.main-container
    %h1.text-center.ntf My Works
    - if current_user && current_user.admin?
      .pull-right.new-work
        %a.no-decoration.btn.btn-xs{href: "#{new_my_work_path}"}
          %span.glyphicon.glyphicon-plus{title: 'New My Work'}
    .row.my-works-images
      - @my_works.each do |my_work|
        .col-lg-3.col-md-3.col-sm-3.col-xs-4
          .my-thumbnail.my-work-links
            .thumbnail-title.text-center.my-work-title{ id: "my-work-title-#{my_work.id}", data: { full: "#{my_work.title}", my_work_id: "#{my_work.id}"} }
              =truncate(my_work.title,length: 18, separator: ' ')
            - if current_user && current_user.admin?
              = render partial: 'admin_options', locals: { my_work: my_work }
            %a{ href: "/my_works/#{my_work.id}" }
              - if my_work.cover?
                %img.picture-ajax.my-work-title.img-responsive{class: "#{my_work.published ? 'published' : 'unpublished'}", data: {id: "#{my_work.cover.id}", size: 'medium', my_work_id: "#{my_work.id}"}}
              - else
                = image_tag('image-not-found.png', class: "thumbnail-img my-work-title #{my_work.published ? 'published' : 'unpublished'}", data: { my_work_id: "#{my_work.id}" })

app/views/my_works/new.html.haml
.row
  .col-sm-10.col-sm-offset-1.main-container
    .row
      .col-sm-10.col-sm-offset-1
        %h1.text-center.ntf New Work

        = render 'form'
        %br
        = link_to 'Back', my_works_path, class: 'btn btn-purple btn-sm'

app/views/my_works/show.html.haml
.row
  .col-sm-10.col-sm-offset-1.main-container#my-work-show
    .visible-xs
      %h1.text-center
        = render partial: 'admin_options', locals: { my_work: @my_work }
        = @my_work.title
      .col-sm-6.remove-right-padding
        .row
          .col-sm-11
            = render partial: 'description'
    .row
      .col-sm-6
        %div.tabbable.tabs-left{:role => "tabpanel"}
          .row
            .col-sm-2.col-sm-offset-1.col-xs-10.col-xs-offset-1#my-work-show-left-tabs
              = render partial: 'thumbnail_list'
            .col-sm-9.hidden-xs
              = render partial: 'full_image'
      .col-sm-6.remove-right-padding.hidden-xs
        .row
          .col-sm-11
            = render partial: 'description'

app/views/my_works/show_off.html.haml
%h1 Listing my_works

%table.table
  %thead
    %tr
      %th Title
      %th Tags
      %th Description
      %th
      %th
      %th
      
  %tbody
    - @my_works.each do |my_work|
      %tr
        %td= my_work.title
        %td= my_work.tags
        %td= my_work.description
        %td= link_to 'Show', my_work
        %td= link_to 'Edit', edit_my_work_path(my_work)
        %td= link_to 'Destroy', my_work, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New My work', new_my_work_path