config/routes.rb
Rails.application.routes.draw do
  resources :pictures

  resources :my_works

  resources :faqs

  resources :users

  root 'static_pages#home'

  get 'about_me', to: 'about_me#show'
  get 'about_me/edit', to: 'about_me#edit'
  post 'about_me/update', to: 'about_me#update'

  get 'contact_me', to: 'contact_me#show'
  get 'contact_me/edit', to: 'contact_me#edit'
  post 'contact_me/update', to: 'contact_me#update'
  post 'contact_me', to: 'contact_me#contact_me'

  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'

  get '/signup' => 'users#new'

end

app/views/layouts/_nav_bar.html.haml
%nav#top-nav-bar.navbar.navbar-bav.navbar-default.nav-justified
  .container-fluid
    %ul.nav.nav-pills.nav-justified
      - selected = selected ? selected.gsub('_',' ').split.map(&:capitalize).join(' ') : nil
      %li{:role => "presentation", class: "#{'active' if selected == t('home')}"}
        %a{:href => "/"} 
          = t('home')
      %li{:role => "presentation", class: "#{'active' if selected == t('contact_me')}"}
        %a{:href => "/contact_me"}
          = t('contact_me')

app/views/layouts/_notifier.html.haml
:javascript
  $(document).ready(function() {
    $('#myModal').modal({
     show: true,
    })

    setTimeout(function(){
      $('#myModal').modal('hide');
    }, 3000);

  });
/ Modal
#myModal.modal.fade{"aria-" => "", "aria-hidden" => "true", :labelledby => "myModalLabel", :role => "dialog", :tabindex => "-1"}
  .modal-dialog
    .modal-content
      .modal-body#mymodal-body
        - flash.each do |key, value|
          %div.flash{ class: "#{key}", id: "#{key}" }
            =value
        

app/views/layouts/_top_nav.html.haml
%nav.navbar.navbar-default.navbar-inverse.navbar-fixed-top#top-nav-bar
  .container-fluid
    / Brand and toggle get grouped for better mobile display
    .navbar-header
      %button.navbar-toggle.collapsed{"data-target" => "#bs-example-navbar-collapse-1", "data-toggle" => "collapse", :type => "button"}
        %span.sr-only Toggle navigation
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      %a.navbar-brand{:href => "/"}
        = image_tag("logo.png", :alt => "Brand", id: 'brand-icon')
    / Collect the nav links, forms, and other content for toggling
    #bs-example-navbar-collapse-1.collapse.navbar-collapse
      - puts params
      - selected = params["controller"] + "_" + params["action"]
      %ul.nav.navbar-nav
        %li{:role => "presentation", class: "#{'active' if selected == 'contact_me_show' }"}
          %a{:href => "/contact_me"}
            = t('contact_me')
        %li{:role => "presentation", class: "#{'active' if selected == 'about_me_show' }"}
          %a{:href => "/about_me"}
            = t('about_me')
        %li{:role => "presentation", class: "#{'active' if selected == 'faqs_index' }"}
          %a{:href => "#{faqs_path}"}
            = t('faq')
        %li{:role => "presentation", class: "#{'active' if ( selected == 'my_works_index' || selected == 'my_works_show') }"}
          %a{:href => "#{my_works_path}"}
            = t('my_work')
      %ul.nav.navbar-nav.navbar-right
        - if current_user
          %li.dropdown
            %a.dropdown-toggle{"aria-expanded" => "false", "data-toggle" => "dropdown", :href => "#", :role => "button"}
              = current_user.email
              %span.caret
            %ul.dropdown-menu{:role => "menu"}
              %li
                %a{:href => "#{user_path(current_user.id)}"} 
                  Profile
              %li.divider
              %li
                %a{:href => "#{logout_path}"} 
                  = t('logout')
        - else
          %li.dropdown
            %a.dropdown-toggle{"data-toggle" => "dropdown", :href => "#"}
              Sign In
              %strong.caret
            .dropdown-menu{:style => "padding: 10px;min-width:240px;"}
              .login-box
                = render partial: 'sessions/new'
                = link_to 'Sign Up/New User', signup_path

app/views/layouts/application.html.haml
!!!
%html{:lang => "en"}
  %head
    - if @subsection
      %title #{ @subsection ? @subsection + ' - ' : '' } Jones Jems
    - elsif params["action"]
      %title #{ params["action"].gsub('_',' ').split.map(&:capitalize).join(' ') } - Jones Jems
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => false
    = javascript_include_tag 'application', 'data-turbolinks-track' => false
    = csrf_meta_tags
    %link{:href => "https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap.min.css", :rel => "stylesheet"}
    %link{:href => "https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap-theme.min.css", :rel => "stylesheet"}
    %link{:href => "//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css", :rel => "stylesheet"}
    = favicon_link_tag 'favicon-clear.ico'
    %script{:src => "https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"}
    %script{:src => "https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/js/bootstrap.min.js"}
    %meta{:content => "width=device-width, initial-scale=1.0", :name => "viewport"}
  %body
    = flash_msg(true)
    = render partial: 'layouts/top_nav'
    - id = 'page-title'
    - pic_id = 'title-image'
    - if params["action"] == "home"
      - id = 'header'
      - pic_id = 'js-center-image'
    .container-fluid
      .row{id: id}
        - unless @header_image && @header_image == "false"
          = image_tag("full_logo.png", :alt => "banner", :id => pic_id, class: 'img-responsive', data: { width: '562', height: '247' })
      - if params["action"] == "home"
        = yield
      - else
        = yield
    %footer